context_alias = "bookstore-dev"

[aws]
symbol = ""
style = 'bold fg:white'
format = '[$symbol(\[AWS\] $profile )]($style)'
force_display = false

[custom.aws_whoami]
format = '[($output )](bold yellow)'
command = 'echo "$AWS_WHOAMI"'

[docker_context]
symbol = ' '
style = 'fg:white'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'

[character]
success_symbol = '[#](bold white)'
error_symbol = '[#](bold white)'

[palettes.nord]
dark_blue = '#5E81AC'
blue = '#81A1C1'
teal = '#88C0D0'
red = '#BF616A'
orange = '#D08770'
green = '#A3BE8C'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#434C5E'
black = '#2E3440'
white = '#D8DEE9'

